spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  security:
#    user:
#      name: aayush
#      password: aayush@123